"""initial schema

Revision ID: 32b436e381e2
Revises: 
Create Date: 2026-08-01 11:36:10.168062
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '32b436e381e2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_asset_id'), 'ai_insights', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_generated_at'), 'ai_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_module'), 'ai_insights', ['module'], unique=False)
    op.create_index(op.f('ix_ai_insights_scope'), 'ai_insights', ['scope'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('asset_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('rated_power_w', sa.Float(), nullable=False),
    sa.Column('nominal_voltage_v', sa.Float(), nullable=False),
    sa.Column('max_temperature_c', sa.Float(), nullable=False),
    sa.Column('max_current_a', sa.Float(), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('device_uid', sa.String(length=48), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution', sa.String(length=8), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('active_power', sa.Float(), nullable=False),
    sa.Column('apparent_power', sa.Float(), nullable=False),
    sa.Column('reactive_power', sa.Float(), nullable=False),
    sa.Column('power_factor', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('runtime_hours', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('relay_status', sa.String(length=8), nullable=False),
    sa.Column('relay_operations', sa.Integer(), nullable=False),
    sa.Column('device_status', sa.String(length=16), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('load_state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_asset_id'), 'telemetry', ['asset_id'], unique=False)
    op.create_index('ix_telemetry_asset_ts', 'telemetry', ['asset_id', 'ts'], unique=False)
    op.create_index(op.f('ix_telemetry_device_uid'), 'telemetry', ['device_uid'], unique=False)
    op.create_index(op.f('ix_telemetry_resolution'), 'telemetry', ['resolution'], unique=False)
    op.create_index('ix_telemetry_resolution_ts', 'telemetry', ['resolution', 'ts'], unique=False)
    op.create_index(op.f('ix_telemetry_ts'), 'telemetry', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_uid', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('anomaly_uid', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('response_target_minutes', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_uid'), 'alerts', ['alert_uid'], unique=True)
    op.create_index(op.f('ix_alerts_anomaly_uid'), 'alerts', ['anomaly_uid'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_raised_at'), 'alerts', ['raised_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('anomaly_detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_uid', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=80), nullable=True),
    sa.Column('error_code', sa.String(length=16), nullable=False),
    sa.Column('anomaly_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('detection_method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_asset_detected', 'anomaly_detection', ['asset_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_anomaly_type'), 'anomaly_detection', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_anomaly_uid'), 'anomaly_detection', ['anomaly_uid'], unique=True)
    op.create_index(op.f('ix_anomaly_detection_asset_id'), 'anomaly_detection', ['asset_id'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_detected_at'), 'anomaly_detection', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_error_code'), 'anomaly_detection', ['error_code'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_severity'), 'anomaly_detection', ['severity'], unique=False)
    op.create_index(op.f('ix_anomaly_detection_status'), 'anomaly_detection', ['status'], unique=False)
    op.create_table('asset_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wear', sa.Float(), nullable=False),
    sa.Column('base_wear_per_day', sa.Float(), nullable=False),
    sa.Column('expected_life_days', sa.Float(), nullable=False),
    sa.Column('last_serviced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_components_asset_id'), 'asset_components', ['asset_id'], unique=False)
    op.create_table('asset_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('uptime_ratio', sa.Float(), nullable=False),
    sa.Column('mtbf_hours', sa.Float(), nullable=False),
    sa.Column('mttr_minutes', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('energy_per_hour', sa.Float(), nullable=False),
    sa.Column('anomalies_24h', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('health_band', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_performance_asset_id'), 'asset_performance', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_performance_computed_at'), 'asset_performance', ['computed_at'], unique=False)
    op.create_index('ix_performance_asset_computed', 'asset_performance', ['asset_id', 'computed_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=48), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('sensor_model', sa.String(length=64), nullable=False),
    sa.Column('firmware_version', sa.String(length=32), nullable=False),
    sa.Column('gateway_id', sa.String(length=48), nullable=False),
    sa.Column('mqtt_topic', sa.String(length=160), nullable=False),
    sa.Column('relay_status', sa.String(length=8), nullable=False),
    sa.Column('relay_operations', sa.Integer(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_asset_id'), 'devices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_devices_device_uid'), 'devices', ['device_uid'], unique=True)
    op.create_table('oee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('oee', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('world_class', sa.Float(), nullable=False),
    sa.Column('availability_loss', sa.Float(), nullable=False),
    sa.Column('performance_loss', sa.Float(), nullable=False),
    sa.Column('quality_loss', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oee_asset_id'), 'oee', ['asset_id'], unique=False)
    op.create_index(op.f('ix_oee_computed_at'), 'oee', ['computed_at'], unique=False)
    op.create_index(op.f('ix_oee_scope'), 'oee', ['scope'], unique=False)
    op.create_table('predictive_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=80), nullable=False),
    sa.Column('wear', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('rul_days', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('maintenance_priority', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictive_asset_component', 'predictive_maintenance', ['asset_id', 'component', 'computed_at'], unique=False)
    op.create_index(op.f('ix_predictive_maintenance_asset_id'), 'predictive_maintenance', ['asset_id'], unique=False)
    op.create_index(op.f('ix_predictive_maintenance_component'), 'predictive_maintenance', ['component'], unique=False)
    op.create_index(op.f('ix_predictive_maintenance_computed_at'), 'predictive_maintenance', ['computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictive_maintenance_computed_at'), table_name='predictive_maintenance')
    op.drop_index(op.f('ix_predictive_maintenance_component'), table_name='predictive_maintenance')
    op.drop_index(op.f('ix_predictive_maintenance_asset_id'), table_name='predictive_maintenance')
    op.drop_index('ix_predictive_asset_component', table_name='predictive_maintenance')
    op.drop_table('predictive_maintenance')
    op.drop_index(op.f('ix_oee_scope'), table_name='oee')
    op.drop_index(op.f('ix_oee_computed_at'), table_name='oee')
    op.drop_index(op.f('ix_oee_asset_id'), table_name='oee')
    op.drop_table('oee')
    op.drop_index(op.f('ix_devices_device_uid'), table_name='devices')
    op.drop_index(op.f('ix_devices_asset_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_performance_asset_computed', table_name='asset_performance')
    op.drop_index(op.f('ix_asset_performance_computed_at'), table_name='asset_performance')
    op.drop_index(op.f('ix_asset_performance_asset_id'), table_name='asset_performance')
    op.drop_table('asset_performance')
    op.drop_index(op.f('ix_asset_components_asset_id'), table_name='asset_components')
    op.drop_table('asset_components')
    op.drop_index(op.f('ix_anomaly_detection_status'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_severity'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_error_code'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_detected_at'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_asset_id'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_anomaly_uid'), table_name='anomaly_detection')
    op.drop_index(op.f('ix_anomaly_detection_anomaly_type'), table_name='anomaly_detection')
    op.drop_index('ix_anomaly_asset_detected', table_name='anomaly_detection')
    op.drop_table('anomaly_detection')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_raised_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_anomaly_uid'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_uid'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_ts'), table_name='telemetry')
    op.drop_index('ix_telemetry_resolution_ts', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_resolution'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_device_uid'), table_name='telemetry')
    op.drop_index('ix_telemetry_asset_ts', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_asset_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_ai_insights_scope'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_module'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_generated_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_asset_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
