"""add telemetry source

Revision ID: 4329b2dea4e6
Revises: a7c41d9e02b8
Create Date: 2026-08-05 17:22:55.610559
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4329b2dea4e6'
down_revision: str | None = 'a7c41d9e02b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('source', sa.String(length=32), nullable=True))
    op.execute("UPDATE telemetry SET source = 'Simulator'")
    op.alter_column('telemetry', 'source', nullable=False)
    op.create_index(op.f('ix_telemetry_source'), 'telemetry', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_source'), table_name='telemetry')
    op.drop_column('telemetry', 'source')
    # ### end Alembic commands ###
