"""Historical back-fill.

Thirty days of history is generated by running the same simulator forward from a
month ago to now, so the stored past and the live present are one continuous
series: energy carries over, wear carries over, and the health on the last
historical row is the health on the first live one.

The sampling is deliberately not per-second. A month of one-second readings is
about 62 million rows per device, which is neither storable on a workstation nor
useful — nobody asks a question of last month's data that needs one-second
resolution. The plan is:

    beyond 7 days   → hourly
    7 days to 24h   → quarter-hourly
    inside 24 hours → per minute
    from now on     → per second, live

Each row records which resolution produced it, so a query can pick the coarsest
one that still answers the question.

Wear accrues at true rate during the back-fill — one day of wear per day of
history. The live engine then runs on an accelerated clock so degradation is
observable within a session; applying that acceleration to a month of history
would age the estate by five years and kill it.
"""

from __future__ import annotations

import time
from datetime import datetime, timedelta, timezone

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.config import settings
from app.logging_config import get_logger
from app.models.telemetry import Telemetry
from app.services.engine import InteloraEngine
from app.services.persistence import persist_anomalies

logger = get_logger(__name__)

CHUNK_ROWS = 5000


def history_present(session: Session) -> bool:
    """True when a back-fill has already been written."""
    oldest = session.execute(select(func.min(Telemetry.ts))).scalar()
    if oldest is None:
        return False
    age_days = (datetime.now(timezone.utc) - oldest).total_seconds() / 86_400.0
    return age_days >= settings.history_days * 0.8


def _phases(now: datetime) -> list[tuple[datetime, datetime, float, str]]:
    """Windows to generate, as (start, end, step seconds, resolution label)."""
    month_ago = now - timedelta(days=settings.history_days)
    week_ago = now - timedelta(days=7)
    day_ago = now - timedelta(hours=24)

    return [
        (month_ago, week_ago, float(settings.backfill_hour_step_seconds), "hour"),
        (week_ago, day_ago, float(settings.backfill_quarter_step_seconds), "quarter"),
        (day_ago, now, float(settings.backfill_minute_step_seconds), "minute"),
    ]


def run_backfill(session: Session, engine: InteloraEngine, now: datetime | None = None) -> int:
    """Generate and store the estate's recent history. Returns rows written."""
    stamp = now or datetime.now(timezone.utc)
    started = time.perf_counter()

    phases = _phases(stamp)
    engine.simulator.rewind_to(phases[0][0])

    buffer: list[dict] = []
    written = 0

    for start, end, step, resolution in phases:
        span = (end - start).total_seconds()
        steps = max(0, int(span // step))
        # Detection runs only at minute resolution. A fault window lasting fifty
        # seconds is genuinely invisible to an hourly sample, and pretending
        # otherwise would put events in the journal the stored data does not
        # support.
        detect = resolution == "minute"

        logger.info(
            "back-filling %s resolution: %d steps of %.0fs from %s",
            resolution,
            steps,
            step,
            start.strftime("%Y-%m-%d %H:%M"),
        )

        for _ in range(steps):
            readings = engine.simulator.step(step, wear_scale=1.0, resolution=resolution)

            if detect:
                for reading in readings:
                    state = engine.simulator.states[reading.asset_id]
                    engine.detector.evaluate(state, reading, step)

            buffer.extend(reading.as_row() for reading in readings)

            if len(buffer) >= CHUNK_ROWS:
                session.bulk_insert_mappings(Telemetry, buffer)
                session.commit()
                written += len(buffer)
                buffer.clear()

    if buffer:
        session.bulk_insert_mappings(Telemetry, buffer)
        session.commit()
        written += len(buffer)

    # Land the simulator exactly on the wall clock so the first live tick
    # continues the series rather than repeating or skipping a stretch of it.
    engine.simulator.rewind_to(stamp)
    engine.history_backfilled = True

    persist_anomalies(session, engine.detector)
    session.commit()

    elapsed = time.perf_counter() - started
    logger.info(
        "back-fill complete: %d telemetry rows and %d reconstructed events in %.1fs",
        written,
        len(engine.detector.journal),
        elapsed,
    )
    return written


def clear_history(session: Session) -> int:
    """Remove every telemetry row. Used by the reset path and by tests."""
    removed = session.query(Telemetry).delete()
    session.commit()
    logger.warning("cleared %d telemetry rows", removed)
    return removed
